# Generated by Django 4.0.1 on 2022-04-01 09:01

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_vacancy_active_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
