# Generated by Django 4.0.1 on 2022-04-01 09:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_alter_resume_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.PositiveIntegerField(blank=True, help_text='998901234567', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
